### PR TITLE
Plumb activation state into parallel steps

### PR DESCRIPTION
**Pull request by mreichhoff**
TODO: activation consumption still TBD.

### CODE REVIEW

**Comment by mreichhoff** [comment]
@domfarolino @johannhof 

this should address the other feedback in [the prior round](https://github.com/privacycg/requestStorageAccessForOrigin/pull/6), other than the goal of consuming user activation in the event that the promise is rejected (which I wanted to ask about, since the only other spec I've found with such a pattern is [SAA](https://github.com/privacycg/storage-access/blob/main/storage-access.bs#L191), which I believe has the same parallelism issue).

**Review by domfarolino — APPROVED** [review]
LGTM. Do you also want to consume activation in the event that you don't reject the promise? I imagine that it should be consumed regardless, no?

**Comment by mreichhoff** [comment]
> I imagine that it should be consumed regardless, no?

There [was a long discussion](https://github.com/privacycg/storage-access/issues/25) about this on the SAA side, and I believe it's still pending on some kind of temporary consumption mechanism. It might be reasonable to consume regardless, though, given the comparative ease of getting activation in this case (vs embedded content). I wonder if @johannhof has any thoughts.

**Review by johannhof — APPROVED** [review]
I think I somewhat prefer sticking to the SAA model of consumption for now. It seems like the most ergonomic model for developers and an okay compromise until we get around to figuring out the "pausing" model (which, admittedly, could take a while).

**Comment by mreichhoff** [comment]
that seems fair...I can leave the consumption as-is (i.e., in the rejection case only) and file an issue to revisit the concern about consuming activation in parallel steps once the temporary consumption mechanism is ready.

**Pull request merged**
